#CVServer CVTradeGW

all:
	(cd CVServer; make all)
	(cd CVTradeGW; make all)
	(cd CVReply; make all)
	(cd CVReplyWS; make all)

clean:
	(cd CVServer; make clean)
	(cd CVTradeGW; make clean)
	(cd CVReply; make clean)
	(cd CVReplyWS; make clean)
