#CVServer CVTradeGW

all:
	(cd CVServer; make all)
	(cd CVTradeGW; make all)
	(cd CVReplyWS; make all)
	(cd CVPnlWS; make all)

clean:
	(cd CVServer; make clean)
	(cd CVTradeGW; make clean)
	(cd CVReplyWS; make clean)
	(cd CVPnlWS; make clean)
