#NETWORK SETTING
IP=127.0.0.1
PORT=8998

#ACCOUNT SETTING
PASSWORD=testtest
USERID=P123456789
USERACC=0000001

#RUNNING PARAMETERS
BEGIN=0
END=0
SILENT=0

NOW=$(date +"%Y%m%d_%H%M%S")

rm -rf ./Report/*.txt;
mkdir -p ./Report
THREADEXP=0

#		ID	PASSWORD	ISLOGIN		LOOPNUM		ORDERNUM	THREADEXP	ACCOUNT		TESTPATH	IP	PORT	EXEC_RESULT
./sslconnect $USERID	$PASSWORD	1		1		1		$THREADEXP	$USERACC 	S		$IP     $PORT	;Result[3]=$?;
