#NETWORK SETTING
IP=192.168.101.211
PORT=2001

#ACCOUNT SETTING
PASSWORD=keanutradetest
USERID=keanu.huang
USERACC=0000001

#RUNNING PARAMETERS
BEGIN=0
END=0
SILENT=0

NOW=$(date +"%Y%m%d_%H%M%S")

rm -rf ./Report/*.txt;
mkdir -p ./Report
THREADEXP=3

#		ID	PASSWORD	ISLOGIN		LOOPNUM		ORDERNUM	THREADEXP	ACCOUNT		TESTPATH	IP	PORT	EXEC_RESULT
./sslconnect $USERID	$PASSWORD	1		1		3		$THREADEXP	$USERACC 	S		$IP     $PORT	;Result[3]=$?;
